---
- name: Install docker-compose pip
  pip:
    name: docker-compose
    state: present

- name: Ensure project directory exists
  file:
    path: "{{ project_dir }}"
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: Deploy docker-compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ project_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: "0600"

- name: Deploy docker container
  docker_compose:
    project_src: "{{ project_dir }}"
    pull: "{{ pull }}"
    state: "{{ container_state }}"
  register: output
